import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '/styles/Home.module.css'
import Nav from '<designscotland>/components/navbar'
import Footer from '<designscotland>/components/footer'
import CatLink from '<designscotland>/components/categoryLinks'
import Accordion from '<designscotland>/components/accordion'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Digital Scotland Design System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <div class="ds_page">
            <div class="ds_page__top">
              <Nav></Nav>
              <div class="ds_wrapper">
                <div class="ds_feature-header hero-banner ds_!_height--500px">
                  <div class="ds_feature-header__primary">
                      <h1 class="ds_feature-header__title">
                        Design standards
                      </h1>
                      <p>
                        The patterns included here have been developed for use by government, public sector and third sector non-commercial organisations in Scotland.
                      </p>
                  </div>

                  <div class="ds_feature-header__secondary">
                      <Image class='ds_!_margin-left--auto ds_!_margin-right--auto ds_!_display--flex ds_!_padding--8' src={"/../public/scotch.png"} width={500} height={500}></Image>
                  </div>
                </div>
              </div>
            </div>

            <div class="ds_page__middle">
                <CatLink></CatLink>

                <div className='category-lower ds_pre-footer-background'>
                  <div className='ds_wrapper ds_!_padding-top--6'>
                    <div className="parent">
                      <div className="div1"> 
                        <div className="ds_page-header">
                          <span className="ds_page-header__label  ds_content-label">
                            Guide
                          </span>
                          <h1 className="ds_page-header__title">
                            Apply for or renew a disabled parking permit
                          </h1>

                          <dl className="ds_page-header__metadata  ds_metadata">
                              <div className="ds_metadata__item">
                                  <dt className="ds_metadata__key">
                                    Last updated
                                  </dt>
                                  <dd className="ds_metadata__value">
                                    8 November 2016
                                  </dd>
                              </div>
                          </dl>
                        </div>
                      </div>

                      <div className="div2">
                        <div>
                          <Accordion></Accordion>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                
            </div>

            <div class="ds_page__bottom">
                <Footer></Footer>
            </div>
        </div>
     </body>
    </>
  )
}
