import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '/styles/Home.module.css'
import Nav from '<designscotland>/components/navbar'
import Footer from '<designscotland>/components/footer'
import CatLink from '<designscotland>/components/categoryLinks'
import Accordion from '<designscotland>/components/accordion'
import Breadcrumbs from '<designscotland>/components/breadcrumbs'
import AspectBox from '<designscotland>/components/aspectBox'
import FileDownload from '<designscotland>/components/fileDownload'
import CharacterCount from '<designscotland>/components/characterCount/characterCount'
import Checkboxes from '<designscotland>/components/checkboxes/checkboxesNoneErr'
import ContactDetails from '<designscotland>/components/contactDetails'
import ErrorMessage from '<designscotland>/components/errorMessage'
import ErrorSummary from '<designscotland>/components/errorSummery'
import FeatureHeader from '<designscotland>/components/featureHeader'
import InsertText from '<designscotland>/components/insertText'
import PageHeader from '<designscotland>/components/pageHeader'
import PhaseBanner from '<designscotland>/components/phaseBanner'
import Question from '<designscotland>/components/question'
import RadioButton from '<designscotland>/components/radioButtons/radioButtonHint'
import SeqNavigation from '<designscotland>/components/sequentialNavigation'
import SideNavigation from '<designscotland>/components/sideNavigation'
import SkipLinks from '<designscotland>/components/skipLinks'
import SummaryList from '<designscotland>/components/summaryList'
import Table from '<designscotland>/components/table'
import Tabs from '<designscotland>/components/tabs'
import WarningText from '<designscotland>/components/warningText'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Digital Scotland Design System
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <div class="ds_page">
            <div class="ds_page__top">

              <Nav/>

              <SkipLinks/>

              <div class="ds_wrapper">
                
                <FeatureHeader/>

              </div>
            </div>

            <div class="ds_page__middle">

            <div className='category-lower ds_pre-footer-background'>
                  <div className='ds_wrapper'>
                    
                    <Breadcrumbs/>
                    
                    <div className="parent">
                      
                      <PageHeader id={'main-content'}/>

                      <div>
                        <Accordion/>
                      </div>
                      
                      
                      <CatLink/>

                      {/* <AspectBox/> */}

                      <FileDownload/>

                      <Checkboxes/>

                      <ErrorMessage/>

                      <ErrorSummary/>

                      <InsertText/>

                      <div>
                        <Question/>
                      </div>

                      <SeqNavigation/>

                      <SideNavigation/>

                      <SummaryList/>

                      <Table/>

                      <Tabs/>

                      <WarningText/>

                    </div>
                </div>
              </div>
                
            </div>

            <div class="ds_page__bottom">

              <div className='ds_wrapper'>
                <div className='parent'>

                  <ContactDetails/>

                </div>
              </div>

              <PhaseBanner/>

              <Footer/>

            </div>
        </div>
      </body>
    </>
  )
}
